const API_BASE_URL_DEVELOPMENT = "https://localhost:7191";

const ENDPOINTS = {
    REGISTRATION: 'registration',
    LOGIN: 'login',
    USER: 'user',
    TEACHER: 'teacher',
    GET_ALL_TEACHERS: 'get-all-teachers',
    TEACHER: 'teacher'
};

const constants = {
    API_URL_REGISTRATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTRATION}`,
    API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN}`,
    API_URL_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.USER}`,
    API_URL_TEACHER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TEACHER}`,
    API_URL_GET_ALL_TEACHERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_TEACHERS}`,
    API_URL_TEACHER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TEACHER}`
}

export default constants;